### ISSUE TITLE
TensorFlow installation with Coach failed

### ISSUE THREAD

**Issue by ViktorM** [NervanaSystems/coach#10]
Hi,

Tried follow installation instructions. But after very long, more than half an hour installation process I found TensorFlow not working when I tried an example script:
```
python coach.py -r -p Pendulum_ClippedPPO -n 8
Traceback (most recent call last):
  File "coach.py", line 23, in <module>
    from architectures import *
  File "/home/viktor/DeepRL/coach/architectures/__init__.py", line 20, in <module>
    from architectures.tensorflow_components.general_network import *
  File "/home/viktor/DeepRL/coach/architectures/tensorflow_components/general_network.py", line 17, in <module>
    from architectures.tensorflow_components.embedders import *
  File "/home/viktor/DeepRL/coach/architectures/tensorflow_components/embedders.py", line 20, in <module>
    class InputEmbedder:
  File "/home/viktor/DeepRL/coach/architectures/tensorflow_components/embedders.py", line 21, in InputEmbedder
    def __init__(self, input_size, activation_function=tf.nn.relu, name="embedder"):
AttributeError: module 'tensorflow' has no attribute 'nn'
```
Also I supposed from the description that it'll install in the virtual env, but instead this installation also has broken my default TensorFlow-GPU installation. So:

1. Why installation is so long? Installtion of the OpenAI baselines with just "pip install -e ." takes less than a minute for example, the same as rllab.
2. How this TF installation bug can be fixed?

**Comment by galleibo-intel** [comment]
Hi Viktor,

1. Coach's installer installs all the dependencies needed for ramping up Coach & Gym (at the bare minimum) over TensorFlow. It makes no assumption on your installed dependencies, and so can be used to install on a vanilla Ubuntu 16.04 image. If one of the dependencies is already installed on your system it will not be installed again (apt-get and pip take care of that). 


2. Unless installed with the --no_virtual_environment flag, Coach should install in a virtualenv. 
a. Are you running Coach from within the virtualenv ("source activate coach_env")?
b. From within the virtualenv, could you please check what is the tensorflow version installed (python -c "import tensorflow; print(tensorflow.__version__)")?

**Comment by itaicaspi-intel** [comment]
About the installation time - it highly depends on your machine, internet connection and if some the packages are already installed. This is an approximate breakdown of the installation time on a clean machine:
* 1:20 mins - initial dependencies (pip, virtualenv etc.)
* 1:40 mins - coach dependencies 
* 07:00 mins - dashboard dependencies (mainly due to wxPython)
* 0:45 mins - openai gym
* 04:45 mins - neon, ngraph and mkl-dnn
* 02:00 mins - tensorflow

If your are short on time, you can choose to install a subset of the requirements in the installation script

**Comment by ViktorM** [comment]
Thanks for the reply, was able to perform clean installation from scratch. Everything is working.

**Comment by lijecaru** [comment]
Hi, I have a similar problem, but cannot do a clean installation from scratch. I installed everything, but when I put `python -c "import tensorflow; print(tensorflow.__version__)"` from within the virtual environment, I get the following: 

```
(coach_env) linda@linda:~$ python -c "import tensorflow; print(tensorflow.__version__)"
Traceback (most recent call last):
  File "/home/linda/coach_env/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/linda/coach_env/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/linda/coach_env/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/linda/coach_env/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/linda/coach_env/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/linda/coach_env/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/linda/coach_env/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/linda/coach_env/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/linda/coach_env/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/linda/coach_env/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/linda/coach_env/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/linda/coach_env/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/linda/coach_env/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```
