### ISSUE TITLE
Error in finding module 'rl_coach.memories.episodic'

### ISSUE THREAD

**Issue by ankdesh** [NervanaSystems/coach#102]
After following the instructions for installation, executing any coach command leads to following error - 

(intel-coach-rl) ankdesh@23edd884604e:~/$ coach -l
Traceback (most recent call last):
  File "/home/ankdesh/virtualenvs/intel-coach-rl/bin/coach", line 7, in <module>
    from rl_coach.coach import main
  File "/home/ankdesh/virtualenvs/intel-coach-rl/lib/python3.5/site-packages/rl_coach/coach.py", line 35, in <module>
    from rl_coach.agents.human_agent import HumanAgentParameters
  File "/home/ankdesh/virtualenvs/intel-coach-rl/lib/python3.5/site-packages/rl_coach/agents/human_agent.py", line 22, in <module>
    from rl_coach.agents.agent import Agent
  File "/home/ankdesh/virtualenvs/intel-coach-rl/lib/python3.5/site-packages/rl_coach/agents/agent.py", line 27, in <module>
    from rl_coach.memories.episodic.episodic_experience_replay import EpisodicExperienceReplay
ImportError: No module named 'rl_coach.memories.episodic'

To reproduce: 
1. Docker image is shared at dockerhub and can be pulled by following command:
`
docker pull ankdesh/cuda9.bash:intel-coach
`
2. Create new virtualenv ( named intel-coach-rl in case above)
3. Do 
`
pip3 install rl_coach
`

**Comment by itaicaspi-intel** [comment]
Hi @ankdesh, thanks for the detailed instructions for reproducing.
The pip package in PyPi is missing some files, and will be updated in the following days. at the meantime, I suggest cloning the repository and installing it by following:
```
git clone http://github.com/NervanaSystems/coach
cd coach
pip3 install -e .
```

**Comment by itaicaspi-intel** [comment]
The pip package was updated in PyPi and `pip install rl-coach` should work now.
I am closing the issue for now. Please reopen if the issue persists.
