### ISSUE TITLE
Installation using pip failed 

### ISSUE THREAD

**Issue by ybj14** [NervanaSystems/coach#112]
After running command `pip3 install rl_coach`, I got the following error message:
```
Collecting rl_coach
  Downloading https://files.pythonhosted.org/packages/95/c9/3e92accfc8f967cda8fd37632ec7ec0a4b5ba71e5a8a4a6df2390adba625/rl-coach-0.10.0.4.tar.gz (223kB)
    100% |████████████████████████████████| 225kB 258kB/s
    Complete output from command python setup.py egg_info:
    /bin/sh: 1: pip: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-kocjns51/rl-coach/setup.py", line 63, in <module>
        shell=True)
      File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['pip install https://anaconda.org/intel/tensorflow/1.6.0/download/tensorflow-1.6.0-cp35-cp35m-linux_x86_64.whl']' returned non-zero exit status 127

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kocjns51/rl-coach/

```

Does anybody encounter the same problem?

**Comment by sohakes** [comment]
Hey, I had a similar error. I'm not sure if exactly the same one, but I think so.

I simply changed what was inside `if not using_GPU:` in `setup.py` to `install_requires.append('tensorflow==1.9.0')`. The downside is that this is not optimized for intel cpu, but the optimized version doesn't work here for some reason (although I do have an intel CPU).

**Comment by galleibo-intel** [comment]
does running ```pip3 install https://anaconda.org/intel/tensorflow/1.6.0/download/tensorflow-1.6.0-cp35-cp35m-linux_x86_64.whl``` directly works for you?

**Comment by galleibo-intel** [comment]
Closing due to inactivity. Please re-open if needed.

**Comment by jamescasbon** [comment]
I think this should be reopened. 

I currently cannot install it without editing setup.py, which is a pain.  Can slim_package option somehow be made available somehow?  The only api I know wouldn't work, I think:

https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

**Comment by galnov** [comment]
You can use the slim package.
It is available [here](https://pypi.org/project/rl-coach-slim/).

**Comment by fangchuan** [comment]
HI, I have same problem, can you tell me how you fixed it?

**Comment by rptallman** [comment]
> does running `pip3 install https://anaconda.org/intel/tensorflow/1.6.0/download/tensorflow-1.6.0-cp35-cp35m-linux_x86_64.whl` directly works for you?

This command works flawlessly for me, but I still get the original error message after trying `pip3 install rl_coach` again. 

This is the full error:

```
Collecting rl_coach
  Using cached https://files.pythonhosted.org/packages/39/d1/2dcf4cb53eba56d679b9f1ba2535d0929aa6a7e9fbf20909480e91a99120/rl-coach-0.11.1.tar.gz
    Complete output from command python setup.py egg_info:
    tensorflow-1.12.0-cp35-cp35m-linux_x86_64.whl is not a supported wheel on this platform.
    You are using pip version 8.1.1, however version 19.0.3 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-q97j4sb0/rl-coach/setup.py", line 73, in <module>
        shell=True)
      File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['pip install https://storage.googleapis.com/intel-optimized-tensorflow/tensorflow-1.12.0-cp35-cp35m-linux_x86_64.whl']' returned non-zero exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-q97j4sb0/rl-coach/
```

The last line is in red if it matters.

I'm running Ubuntu 16.04.

**Comment by galnov** [comment]
There have been a few changes since this was last encountered. Specifically, modification of Tensorflow package version in setup.py. If this is still encountered - please reopen.
