### ISSUE TITLE
Circular import in DQN

### ISSUE THREAD

**Issue by varun-intel** [NervanaSystems/coach#128]
Trying to import the DQN model throws an error because of a circular import:
>>> from rl_coach.agents.dqn_agent import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ec/fm/disks/nrv_algo_home01/vvkumar/envs/graphrl/github/NervanaSystems/coach/rl_coach/agents/dqn_agent.py", line 28, in <module>
    from rl_coach.exploration_policies.e_greedy import EGreedyParameters
  File "/ec/fm/disks/nrv_algo_home01/vvkumar/envs/graphrl/github/NervanaSystems/coach/rl_coach/exploration_policies/__init__.py", line 26, in <module>
    from .parameter_noise import ParameterNoiseParameters, ParameterNoise
  File "/ec/fm/disks/nrv_algo_home01/vvkumar/envs/graphrl/github/NervanaSystems/coach/rl_coach/exploration_policies/parameter_noise.py", line 21, in <module>
    from rl_coach.agents.dqn_agent import DQNAgentParameters
ImportError: cannot import name 'DQNAgentParameters'

**Comment by varun-intel** [comment]
My code works if you repeat the import a second time:
try:
    from rl_coach.agents.ddqn_agent import DDQNAgentParameters
except ImportError:
    from rl_coach.agents.ddqn_agent import DDQNAgentParameters

**Comment by galleibo-intel** [comment]
Hi,

I have pushed a PR fixing the issue. Should be merged some time soon.
