### ISSUE TITLE
Issues with tensorflow-gpu>=1.9.0!

### ISSUE THREAD

**Issue by biggzlar** [NervanaSystems/coach#157]
Running the command `pip3 install rl_coach` comes back with the following error message:

```
Collecting tensorflow-gpu>=1.9.0 (from rl_coach)
  Could not find a version that satisfies the requirement tensorflow-gpu>=1.9.0 (from rl_coach) (from versions: )
No matching distribution found for tensorflow-gpu>=1.9.0 (from rl_coach)
```

**Comment by lijecaru** [comment]
Hi, I have a similar issue with tensorflow. When I put 
`pip show tensorflow-gpu
`
I get:

```
Name: tensorflow-gpu
Version: 1.13.1
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /home/linda/coach_env/lib/python3.5/site-packages
Requires: keras-applications, tensorboard, protobuf, six, wheel, astor, tensorflow-estimator, absl-py, termcolor, keras-preprocessing, grpcio, numpy, gast
Required-by: rl-coach
```
But when I try to run the first example `coach -r -p CartPole_PG` i get the following: 

`Traceback (most recent call last):
  File "/home/linda/coach_env/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/linda/coach_env/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/linda/coach_env/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/linda/coach_env/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/linda/coach_env/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linda/coach_env/lib/python3.5/site-packages/rl_coach/architectures/network_wrapper.py", line 46, in __init__
    import tensorflow as tf
  File "/home/linda/coach_env/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/linda/coach_env/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/linda/coach_env/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/linda/coach_env/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/linda/coach_env/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/linda/coach_env/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/linda/coach_env/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/linda/coach_env/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linda/coach_env/bin/coach", line 10, in <module>
    sys.exit(main())
  File "/home/linda/coach_env/lib/python3.5/site-packages/rl_coach/coach.py", line 700, in main
    launcher.launch()
  File "/home/linda/coach_env/lib/python3.5/site-packages/rl_coach/coach.py", line 215, in launch
    self.run_graph_manager(graph_manager, args)
  File "/home/linda/coach_env/lib/python3.5/site-packages/rl_coach/coach.py", line 625, in run_graph_manager
    self.start_single_threaded(task_parameters, graph_manager, args)
  File "/home/linda/coach_env/lib/python3.5/site-packages/rl_coach/coach.py", line 631, in start_single_threaded
    start_graph(graph_manager=graph_manager, task_parameters=task_parameters)
  File "/home/linda/coach_env/lib/python3.5/site-packages/rl_coach/coach.py", line 76, in start_graph
    graph_manager.create_graph(task_parameters)
  File "/home/linda/coach_env/lib/python3.5/site-packages/rl_coach/graph_managers/graph_manager.py", line 144, in create_graph
    self.level_managers, self.environments = self._create_graph(task_parameters)
  File "/home/linda/coach_env/lib/python3.5/site-packages/rl_coach/graph_managers/basic_rl_graph_manager.py", line 59, in _create_graph
    level_manager = LevelManager(agents=agent, environment=env, name="main_level")
  File "/home/linda/coach_env/lib/python3.5/site-packages/rl_coach/level_manager.py", line 88, in __init__
    self.build()
  File "/home/linda/coach_env/lib/python3.5/site-packages/rl_coach/level_manager.py", line 152, in build
    [agent.set_environment_parameters(spaces) for agent in self.agents.values()]
  File "/home/linda/coach_env/lib/python3.5/site-packages/rl_coach/level_manager.py", line 152, in <listcomp>
    [agent.set_environment_parameters(spaces) for agent in self.agents.values()]
  File "/home/linda/coach_env/lib/python3.5/site-packages/rl_coach/agents/agent.py", line 299, in set_environment_parameters
    self.init_environment_dependent_modules()
  File "/home/linda/coach_env/lib/python3.5/site-packages/rl_coach/agents/agent.py", line 344, in init_environment_dependent_modules
    self.networks = self.create_networks()
  File "/home/linda/coach_env/lib/python3.5/site-packages/rl_coach/agents/agent.py", line 317, in create_networks
    worker_device=self.worker_device)
  File "/home/linda/coach_env/lib/python3.5/site-packages/rl_coach/architectures/network_wrapper.py", line 48, in __init__
    raise Exception('Install tensorflow before using it as framework')
Exception: Install tensorflow before using it as framework
`
I don't understand. It seems that tensorflow is installed but coach doesn't recognize it?

**Comment by galleibo-intel** [comment]
It seems that there's an issue with your CUDA installation. This is unrelated to coach. 
Try to open a Python terminal (with the new installed coach_env) and import tensorflow, it should show the same error.
