### ISSUE TITLE
Human control for Carla

### ISSUE THREAD

**Issue by moh3th1** [NervanaSystems/coach#173]
I was tracing how to control Carla using ```Human Control``` that supported in your code. I started by enabling the human control in ```carla_enviroment```. But I faced with this error 

![screenshot from 2018-12-24 12-14-08](https://user-images.githubusercontent.com/15180702/50396883-6515b400-0775-11e9-84f9-a5bca08dbeb9.png)

```Traceback (most recent call last):
  File "/home/lamin/PycharmProjects/untitled/rl_coach/coach.py", line 704, in <module>
    main()
  File "/home/lamin/PycharmProjects/untitled/rl_coach/coach.py", line 700, in main
    launcher.launch()
  File "/home/lamin/PycharmProjects/untitled/rl_coach/coach.py", line 216, in launch
    self.run_graph_manager(graph_manager, args)
  File "/home/lamin/PycharmProjects/untitled/rl_coach/coach.py", line 625, in run_graph_manager
    self.start_single_threaded(task_parameters, graph_manager, args)
  File "/home/lamin/PycharmProjects/untitled/rl_coach/coach.py", line 631, in start_single_threaded
    start_graph(graph_manager=graph_manager, task_parameters=task_parameters)
  File "/home/lamin/PycharmProjects/untitled/rl_coach/coach.py", line 77, in start_graph
    graph_manager.create_graph(task_parameters)
  File "/home/lamin/PycharmProjects/untitled/rl_coach/graph_managers/graph_manager.py", line 144, in create_graph
    self.level_managers, self.environments = self._create_graph(task_parameters)
  File "/home/lamin/PycharmProjects/untitled/rl_coach/graph_managers/basic_rl_graph_manager.py", line 59, in _create_graph
    level_manager = LevelManager(agents=agent, environment=env, name="main_level")
  File "/home/lamin/PycharmProjects/untitled/rl_coach/level_manager.py", line 88, in __init__
    self.build()
  File "/home/lamin/PycharmProjects/untitled/rl_coach/level_manager.py", line 152, in build
    [agent.set_environment_parameters(spaces) for agent in self.agents.values()]
  File "/home/lamin/PycharmProjects/untitled/rl_coach/level_manager.py", line 152, in <listcomp>
    [agent.set_environment_parameters(spaces) for agent in self.agents.values()]
  File "/home/lamin/PycharmProjects/untitled/rl_coach/agents/agent.py", line 301, in set_environment_parameters
    self.init_environment_dependent_modules()
  File "/home/lamin/PycharmProjects/untitled/rl_coach/agents/agent.py", line 343, in init_environment_dependent_modules
    self.exploration_policy = dynamic_import_and_instantiate_module_from_params(self.ap.exploration)
  File "/home/lamin/PycharmProjects/untitled/rl_coach/utils.py", line 418, in dynamic_import_and_instantiate_module_from_params
    return short_dynamic_import(path)(*positional_args, **args)
  File "/home/lamin/PycharmProjects/untitled/rl_coach/exploration_policies/ou_process.py", line 53, in __init__
    self.mu = float(mu) * np.ones(self.action_space.shape)
AttributeError: 'PartialDiscreteActionSpaceMap' object has no attribute 'shape'```

**Comment by galnov** [comment]
Imitation learning for CARLA, and, in general, for continuous control challenges, is currently not supported.
This is tracked in issue #172 , so closing this as a duplicate.
