### ISSUE TITLE
raise exception_type, self._exception, self._traceback

### ISSUE THREAD

**Issue by BoChang11** [NervanaSystems/coach#208]
Hi,

I work on Autonomous vehicle and this is one of the best repository which I found very useful and can use it as reference for future work.

I have started setting up coach as mentioned in the instruction. And unfortunately I am getting error at the beginning steps itself. Could you please help me to fix this.

I have completed the pre-requisites and activated the virtual environment. When I try to install rl_coach using either ```pip3 install rl_coach``` or ```pip3 install -e .```, I am getting the below exception.

```
(coach_env) kishor@GWMIDC-LAP-0037:~$ pip3 install rl_coach
Traceback (most recent call last):
  File "/home/kishor/coach_env/bin/pip3", line 7, in <module>
    from pip._internal import main
  File "/usr/local/lib/python2.7/dist-packages/pip/__init__.py", line 45, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pip/vcs/subversion.py", line 9, in <module>
    from pip.index import Link
  File "/usr/local/lib/python2.7/dist-packages/pip/index.py", line 31, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 6, in <module>
    import compileall
  File "/usr/lib/python3.5/compileall.py", line 20, in <module>
    from concurrent.futures import ProcessPoolExecutor
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 414
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax
```
I am just wondering why it is pointing to python2.7 packages and is it good idea to edit the ```_base.py``` to get rid off this error. 

BR

**Comment by galnov** [comment]
@BoChang11 Have you created your virtualenv with Python 3 (i.e. used the "-p python3" parameter)?

**Comment by galnov** [comment]
Closing due to no response.
