### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by aGiant** [NervanaSystems/coach#255]
Tried to install coach but got error>

```
pip install intel-tensorflow
pip3 install rl_coach


Collecting rl_coach
  Using cached https://files.pythonhosted.org/packages/39/d1/2dcf4cb53eba56d679b9f1ba2535d0929aa6a7e9fbf20909480e91a99120/rl-coach-0.11.1.tar.gz
    Complete output from command python setup.py egg_info:
    tensorflow-1.12.0-cp35-cp35m-linux_x86_64.whl is not a supported wheel on this platform.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7tnb9bb9/rl-coach/setup.py", line 73, in <module>
        shell=True)
      File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['pip install https://storage.googleapis.com/intel-optimized-tensorflow/tensorflow-1.12.0-cp35-cp35m-linux_x86_64.whl']' returned non-zero exit status 1.
```

**Comment by shadiendrawis** [comment]
Should be fixed with PR #281.
