### ISSUE TITLE
Can’t use LSTM as Middleware

### ISSUE THREAD

**Issue by eyyi** [NervanaSystems/coach#26]
Hi

First of all, thank you for this convenient and cool library. 

During my experimentations, I couldn’t figure it out how to use the LSTM Middleware. 
I tested it on two different environments (CartPole and VizDoom Basic) and i got this error message: 

```python
Traceback (most recent call last):
  File "./parallel_actor.py", line 165, in <module>
    agent.improve()
  File "/code/coach/agents/agent.py", line 503, in improve
    self.act()
  File "/code/coach/agents/agent.py", line 435, in act
    self.reset_game()
  File "/code/coach/agents/agent.py", line 201, in reset_game
    network.curr_rnn_c_in = network.middleware_embedder.c_init
AttributeError: 'NetworkWrapper' object has no attribute 'middleware_embedder'
```

I used the following preset:
```python
class Doom_Basic_A3C(Preset):
    def __init__(self):
        Preset.__init__(self, ActorCritic, Doom, CategoricalExploration)
        self.env.level = 'basic'
        self.agent.policy_gradient_rescaler = 'A_Value'
        self.learning_rate = 0.0001
        self.num_heatup_steps = 100
        self.env.reward_scaling = 100.
        self.agent.discount = 0.99
        self.agent.apply_gradients_every_x_episodes = 1
        self.agent.num_steps_between_gradient_updates = 30
        self.agent.beta_entropy = 0.01
        self.clip_gradients = 40
        self.agent.middleware_type = MiddlewareTypes.LSTM
```

I run the experiment with this command:
```python
python3 coach.py -v -p Doom_Basic_A3C -dg -e test_lstm_v1 -s 100 -n 16 -cp "num_training_iterations=1000; evaluation_episodes=100; evaluate_every_x_episodes=500"
```

Did I forget something to configure?

Thanks in advance!
BR, Gabriel

**Comment by itaicaspi-intel** [comment]
Thanks for bringing this up Gabriel.
Your usage example is ok.
This was an issue that should be fixed following commit eeb3ec5497cc4f7ced35ef8754755706f96bf133.
