### ISSUE TITLE
Install coach failed

### ISSUE THREAD

**Issue by fangchuan** [NervanaSystems/coach#271]
Hi, recently I had the same errors when I try to install the coach, whether I used the `pip3 install -e .` or `pip3 install rl_coach` , these command outputs same error information:

`(intel_coach) fc@fc-msi:~/toolkits/ReinforcementLearning/Coach/intel_coach/coach$ pip3 install -e .
Obtaining file:///home/fc/toolkits/ReinforcementLearning/Coach/intel_coach/coach
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/fc/toolkits/ReinforcementLearning/Coach/intel_coach/lib/python3.5/site-packages/setuptools/__init__.py", line 18, in <module>
        import setuptools.version
      File "/home/fc/toolkits/ReinforcementLearning/Coach/intel_coach/lib/python3.5/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/home/fc/toolkits/ReinforcementLearning/Coach/intel_coach/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2927, in <module>
        @_call_aside
      File "/home/fc/toolkits/ReinforcementLearning/Coach/intel_coach/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
        f(*args, **kwargs)
      File "/home/fc/toolkits/ReinforcementLearning/Coach/intel_coach/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
        add_activation_listener(lambda dist: dist.activate())
      File "/home/fc/toolkits/ReinforcementLearning/Coach/intel_coach/lib/python3.5/site-packages/pkg_resources/__init__.py", line 956, in subscribe
        callback(dist)
      File "/home/fc/toolkits/ReinforcementLearning/Coach/intel_coach/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2952, in <lambda>
        add_activation_listener(lambda dist: dist.activate())
      File "/home/fc/toolkits/ReinforcementLearning/Coach/intel_coach/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2515, in activate
        declare_namespace(pkg)
      File "/home/fc/toolkits/ReinforcementLearning/Coach/intel_coach/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/home/fc/toolkits/ReinforcementLearning/Coach/intel_coach/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "/home/fc/toolkits/ReinforcementLearning/Coach/intel_coach/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'
    
`
Is there anybody who can help me? I'm hurry, thanks

**Comment by galleibo-intel** [comment]
Hi, there's seems to be something messy with your environment. Have you tried installing in a clean virtual_env?

**Comment by fangchuan** [comment]
Hi, thanks @galleibo-intel , I tried to install coach in a clean virtual_env and it works. 
However, when I want to run the preset of CARLA_DDPG, it always crashes when it comes to "Starting to improve simple_rl_graph task index 0":
` coach -r -p CARLA_DDPG
Please enter an experiment name: CARLA_DDPG

Creating graph - name: BasicRLGraphManager
Creating agent - name: agent
simple_rl_graph: Starting heatup
Heatup - Name: main_level/agent Worker: 0 Episode: 1 Total reward: -5929.35 Steps: 999 Training iteration: 0 
Heatup - Name: main_level/agent Worker: 0 Episode: 2 Total reward: -607.95 Steps: 1097 Training iteration: 0 
Starting to improve simple_rl_graph task index 0
Segment fault....
`
I have seen the worker_0.simple_rl_graph_0.json , is it possible caused by the memory size of replay buffer? The original size is 1M, while I only have 8G memory on my computer.

**Comment by galleibo-intel** [comment]
Generally, it might pose a problem, but not so early in the process, as the replay buffer is not filled yet. Closing this issue, as the issue was resolved.
