### ISSUE TITLE
TypeError: apply_gradients() got an unexpected keyword argument 'additional_inputs'

### ISSUE THREAD

**Issue by nhivoqb** [NervanaSystems/coach#400]
Hi,

I was testing mxnet framework and run Coach with the command: 
coach -p CartPole_PPO -s 1 --framework mxnet

I got the error below, which seems to occur only with mxnet, not with tensorflow backend. Is there any workaround without editing the "network_wrapper.py" file?

Thanks.

rl_coach version: 1.0.0 installed on virtual environment in Ubuntu vm.

`
/home/nhi/coach_env/lib/python3.6/site-packages/rl_coach/architectures/mxnet_components/heads/head.py:112: UserWarning: Parameter clippedppolosscontinuous0_kl_coefficient is not used by any computation. Is this intended?
  outputs = super(HeadLoss, self).forward(*args)
Traceback (most recent call last):
  File "/home/nhi/coach_env/bin/coach", line 10, in <module>
    sys.exit(main())
  File "/home/nhi/coach_env/lib/python3.6/site-packages/rl_coach/coach.py", line 775, in main
    launcher.launch()
  File "/home/nhi/coach_env/lib/python3.6/site-packages/rl_coach/coach.py", line 224, in launch
    self.run_graph_manager(graph_manager, args)
  File "/home/nhi/coach_env/lib/python3.6/site-packages/rl_coach/coach.py", line 610, in run_graph_manager
    self.start_single_threaded(task_parameters, graph_manager, args)
  File "/home/nhi/coach_env/lib/python3.6/site-packages/rl_coach/coach.py", line 672, in start_single_threaded
    start_graph(graph_manager=graph_manager, task_parameters=task_parameters)
  File "/home/nhi/coach_env/lib/python3.6/site-packages/rl_coach/coach.py", line 87, in start_graph
    graph_manager.improve()
  File "/home/nhi/coach_env/lib/python3.6/site-packages/rl_coach/graph_managers/graph_manager.py", line 549, in improve
    self.train_and_act(self.steps_between_evaluation_periods)
  File "/home/nhi/coach_env/lib/python3.6/site-packages/rl_coach/graph_managers/graph_manager.py", line 484, in train_and_act
    self.train()
  File "/home/nhi/coach_env/lib/python3.6/site-packages/rl_coach/graph_managers/graph_manager.py", line 410, in train
    [manager.train() for manager in self.level_managers]
  File "/home/nhi/coach_env/lib/python3.6/site-packages/rl_coach/graph_managers/graph_manager.py", line 410, in <listcomp>
    [manager.train() for manager in self.level_managers]
  File "/home/nhi/coach_env/lib/python3.6/site-packages/rl_coach/level_manager.py", line 187, in train
    [agent.train() for agent in self.agents.values()]
  File "/home/nhi/coach_env/lib/python3.6/site-packages/rl_coach/level_manager.py", line 187, in <listcomp>
    [agent.train() for agent in self.agents.values()]
  File "/home/nhi/coach_env/lib/python3.6/site-packages/rl_coach/agents/clipped_ppo_agent.py", line 319, in train
    self.train_network(batch, self.ap.algorithm.optimization_epochs)
  File "/home/nhi/coach_env/lib/python3.6/site-packages/rl_coach/agents/clipped_ppo_agent.py", line 251, in train_network
    inputs, [value_targets, batch.info('advantage')[start:end]], additional_fetches=fetches
  File "/home/nhi/coach_env/lib/python3.6/site-packages/rl_coach/architectures/network_wrapper.py", line 175, in train_and_sync_networks
    self.apply_gradients_and_sync_networks(reset_gradients=False)
  File "/home/nhi/coach_env/lib/python3.6/site-packages/rl_coach/architectures/network_wrapper.py", line 203, in apply_gradients_and_sync_networks
    additional_inputs=additional_inputs)
TypeError: apply_gradients() got an unexpected keyword argument 'additional_inputs'
`

**Comment by gal-leibovich** [comment]
Hi @nhivoqb, I'm sorry but unfortunately the mxnet code is not so much maintained at the moment.
