### ISSUE TITLE
Error in 'create_environment'

### ISSUE THREAD

**Issue by TairuiWang** [NervanaSystems/coach#51]
Hi, I just follow the installation instruction on the [website](http://coach.nervanasys.com/usage/index.html). My coach version is '0.9'. 
When use the example command 'python coach.py -p CartPole_DQN'
I got this error:

> Warning: failed to import the following packages - Neon, ViZDoom, RoboSchool, GymExtensions, PyBullet
> Please enter an experiment name: qwer
> Using tensorflow framework
> Traceback (most recent call last):
>   File "coach.py", line 295, in <module>
>     env_instance = create_environment(tuning_parameters)
>   File "/home/terry/robot_proj/intel_coach/coach-0.9.0/environments/__init__.py", line 32, in create_environment
>     env = eval(env_type)(tuning_parameters)
>   File "/home/terry/anaconda3/envs/py35/lib/python3.5/site-packages/pandas/core/computation/eval.py", line 267, in eval
>     ret = eng_inst.evaluate()
>   File "/home/terry/anaconda3/envs/py35/lib/python3.5/site-packages/pandas/core/computation/engines.py", line 75, in evaluate
>     res = self._evaluate()
>   File "/home/terry/anaconda3/envs/py35/lib/python3.5/site-packages/pandas/core/computation/engines.py", line 122, in _evaluate
>     return ne.evaluate(s, local_dict=scope, truediv=truediv)
>   File "/home/terry/anaconda3/envs/py35/lib/python3.5/site-packages/numexpr/necompiler.py", line 789, in evaluate
>     zip(names, arguments)]
>   File "/home/terry/anaconda3/envs/py35/lib/python3.5/site-packages/numexpr/necompiler.py", line 788, in <listcomp>
>     signature = [(name, getType(arg)) for (name, arg) in
>   File "/home/terry/anaconda3/envs/py35/lib/python3.5/site-packages/numexpr/necompiler.py", line 686, in getType
>     raise ValueError("unknown type %s" % a.dtype.name)
> ValueError: unknown type object

I printed out 'env_type' and 'tuning_parameters'. They are:
GymEnvironmentWrapper
<presets.CartPole_DQN object at 0x7f30e7ce09e8>

[Update]
It turns out eval('GymEnvironmentWrapper') is the reason of this error. However, 'GymEnvironmentWrapper' is imported from 'from environments.gym_environment_wrapper import *'  at the top of the script. 

Thanks a lot if anybody has the idea.

**Comment by TairuiWang** [comment]
I solved this problem by create a new clean virtual environment.
