### ISSUE TITLE
Error with Vizdoom

### ISSUE THREAD

**Issue by nina124** [NervanaSystems/coach#69]
It seems there is something wrong with the Vizdoom environment.
I try `VIZDOOM_ROOT=/home/nina/ViZDoom python3 coach.py -p Doom_Basic_Dueling_DDQN`  , but receive the following error.
> Traceback (most recent call last):
  File "coach.py", line 271, in <module>
    env_instance = create_environment(tuning_parameters)
  File "/home/nina/test/RL/coach/environments/__init__.py", line 32, in create_environment
    env = eval(env_type)(tuning_parameters)
  File "/home/nina/test/RL/coach/environments/doom_environment_wrapper.py", line 132, in __init__
    self.reset()
  File "/home/nina/test/RL/coach/environments/environment_wrapper.py", line 171, in reset
    self._update_state()
  File "/home/nina/test/RL/coach/environments/doom_environment_wrapper.py", line 140, in _update_state
    'measurements': state.game_variables,
  File "/home/nina/test/RL/coach/environments/environment_wrapper.py", line 81, in observation
    assert False
AssertionError

**Comment by RLWJR** [comment]
I'm getting the same thing......  Anyone?

**Comment by zach-nervana** [comment]
Try replacing self.observation with self.state on line 138 of doom_environment_wrapper.py

If that does it, I'll submit a PR when i get to a computer later.



Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by nina124** [comment]
hi @zach-nervana ,
Thanks for your reply.
I have modified as you suggested. It started trianing, but the training reward and test reward maintain -300 after one day and a half's training. The running command is `VIZDOOM_ROOT=/home/nina/ViZDoom python3 coach.py -p Doom_Basic_Dueling_DDQN -n 16`.
I tried to play myself to figure out what the '-300 reward'  means, with ``VIZDOOM_ROOT=/home/nina/ViZDoom python3 coach.py -p Doom_Basic_Dueling_DDQN --play`.
After given an 'ATTACK' action, it returns the foolowing error:
> Traceback (most recent call last):
  File "coach.py", line 278, in <module>
    agent.improve()
  File "/home/nina/test/RL/coach/agents/agent.py", line 551, in improve
    self.act()
  File "/home/nina/test/RL/coach/agents/agent.py", line 394, in act
    result = self.env.step(action)
  File "/home/nina/test/RL/coach/environments/environment_wrapper.py", line 143, in step
    self.render()
  File "/home/nina/test/RL/coach/environments/environment_wrapper.py", line 157, in render
    self.renderer.render_image(self.get_rendered_image())
  File "/home/nina/test/RL/coach/renderer.py", line 44, in render_image
    if len(image.shape) == 2:
AttributeError: 'LazyStack' object has no attribute 'shape'

**Comment by itaicaspi-intel** [comment]
Thanks @nina124.
In the new version of Coach, this should work fine.
Try running a single worker using `coach -p Doom_Basic_Dueling_DDQN`. 
It should train in several minutes.
