### ISSUE TITLE
Pandas eval overriding python eval

### ISSUE THREAD

**Issue by bbalaji-ucsd** [NervanaSystems/coach#99]
The way you are importing "from pandas import *" in https://github.com/NervanaSystems/coach/blob/master/logger.py#L17

is causing pandas eval to be imported and overrides python eval.

Since the environment initialization is using "from logger import *" as well:
https://github.com/NervanaSystems/coach/blob/master/environments/__init__.py#L17

When I run eval(env_type)(tuning_parameters) in:
https://github.com/NervanaSystems/coach/blob/master/environments/__init__.py#L31

It gives me the following error:
Traceback (most recent call last):
  File "coach.py", line 271, in <module>
    env_instance = create_environment(tuning_parameters)
  File "../coach/environments/__init__.py", line 32, in create_environment
    env = eval(env_type)(tuning_parameters)
  File "/anaconda3/lib/python3.6/site-packages/pandas/core/computation/eval.py", line 296, in eval
    ret = eng_inst.evaluate()
  File "/anaconda3/lib/python3.6/site-packages/pandas/core/computation/engines.py", line 76, in evaluate
    res = self._evaluate()
  File "/anaconda3/lib/python3.6/site-packages/pandas/core/computation/engines.py", line 123, in _evaluate
    return ne.evaluate(s, local_dict=scope, truediv=truediv)
  File "/anaconda3/lib/python3.6/site-packages/numexpr/necompiler.py", line 807, in evaluate
    zip(names, arguments)]
  File "/anaconda3/lib/python3.6/site-packages/numexpr/necompiler.py", line 806, in <listcomp>
    signature = [(name, getType(arg)) for (name, arg) in
  File "/anaconda3/lib/python3.6/site-packages/numexpr/necompiler.py", line 704, in getType
    raise ValueError("unknown type %s" % a.dtype.name)
ValueError: unknown type object

Because this the default example does not work: python coach.py -p CartPole_DQN

**Comment by bbalaji-ucsd** [comment]
Fix: 
import pandas as pd
...
...
variable_name = pd.DataFrame()

**Comment by itaicaspi-intel** [comment]
Thanks @bbalaji-ucsd.
This was indeed a major potential source for bugs.
Pandas eval function is not used anymore in the new version of coach.
